# Generated by Django 3.0.6 on 2020-09-28 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=50)),
                ('Last_name', models.CharField(max_length=50)),
                ('Email_id', models.EmailField(max_length=50)),
                ('Phone_no', models.CharField(max_length=11)),
            ],
        ),
    ]
